#!/usr/bin/env python3
"""
Evaluate the saved entity-resolution model on a reproducible labeled
training holdout.

This is a diagnostic evaluation only. The official competition/test score
requires submission because the test ground truth is hidden.
"""

import argparse
import os
import sys
from typing import Dict, Set

import numpy as np
import polars as pl
from tqdm import tqdm


# ---------------------------------------------------------------------------
# Path setup
# ---------------------------------------------------------------------------

_ROOT = os.path.dirname(os.path.abspath(__file__))
_SRC = os.path.join(_ROOT, "src")

if _SRC not in sys.path:
    sys.path.insert(0, _SRC)


# ---------------------------------------------------------------------------
# Project imports
# ---------------------------------------------------------------------------

from blocking import build_country_inverted_index, retrieve_candidates_for_s1
from features import compute_pair_features
from metrics import compute_macro_f05
from model import EntityResolutionModel
from pipeline import _load_tsv, _s23_lookup


# ---------------------------------------------------------------------------
# Ground truth
# ---------------------------------------------------------------------------

def _ground_truth(path: str) -> Dict[str, Set[str]]:
    """
    Load training ground truth.

    Returns:
        {
            source1_entity_id: {matched_entity_id, ...}
        }
    """
    frame = _load_tsv(path)

    result: Dict[str, Set[str]] = {}

    for sid, raw_matches in frame.select(
        ["source1_entity_id", "matched_entity_ids"]
    ).iter_rows():

        if raw_matches:
            result[sid] = set(
                match.strip()
                for match in raw_matches.split(",")
                if match.strip()
            )
        else:
            result[sid] = set()

    return result


# ---------------------------------------------------------------------------
# Reproducible holdout selection
# ---------------------------------------------------------------------------

def _holdout_ids(
    gt_ids,
    sample_size: int,
    seed: int,
) -> list[str]:

    ids = np.asarray(gt_ids, dtype=object)

    rng = np.random.default_rng(seed)
    rng.shuffle(ids)

    return ids[: min(sample_size, len(ids))].tolist()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:

    parser = argparse.ArgumentParser(
        description=(
            "Evaluate the saved entity-resolution model on a "
            "labeled training holdout."
        )
    )

    parser.add_argument(
        "--train-dir",
        default="dataset/train",
        help="Directory containing train_source1.tsv, train_source2.tsv, "
             "train_source3.tsv and train_ground_truth.tsv.",
    )

    parser.add_argument(
        "--model-path",
        default="code/business_entity_resolution/model.pkl",
        help="Path to the saved trained model.",
    )

    parser.add_argument(
        "--sample-size",
        type=int,
        default=20000,
        help="Number of Source-1 entities to evaluate.",
    )

    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for reproducible holdout selection.",
    )

    parser.add_argument(
        "--max-candidates",
        type=int,
        default=20,
        help="Maximum candidates generated by the blocking stage.",
    )

    args = parser.parse_args()

    # -----------------------------------------------------------------------
    # Resolve paths
    # -----------------------------------------------------------------------

    train_dir = os.path.abspath(args.train_dir)
    model_path = os.path.abspath(args.model_path)

    ground_truth_path = os.path.join(
        train_dir,
        "train_ground_truth.tsv",
    )

    source1_path = os.path.join(
        train_dir,
        "train_source1.tsv",
    )

    source2_path = os.path.join(
        train_dir,
        "train_source2.tsv",
    )

    source3_path = os.path.join(
        train_dir,
        "train_source3.tsv",
    )

    print("=" * 70)
    print("ENTITY RESOLUTION HOLDOUT EVALUATION")
    print("=" * 70)

    print(f"Train directory : {train_dir}")
    print(f"Model path      : {model_path}")
    print(f"Sample size     : {args.sample_size:,}")
    print(f"Seed            : {args.seed}")
    print(f"Max candidates  : {args.max_candidates}")
    print()

    # -----------------------------------------------------------------------
    # Validate files
    # -----------------------------------------------------------------------

    required_files = [
        ground_truth_path,
        source1_path,
        source2_path,
        source3_path,
        model_path,
    ]

    for path in required_files:
        if not os.path.exists(path):
            raise FileNotFoundError(
                f"Required file not found:\n{path}"
            )

    # -----------------------------------------------------------------------
    # Load ground truth
    # -----------------------------------------------------------------------

    print("Loading ground truth...")

    gt = _ground_truth(ground_truth_path)

    print(f"Ground-truth entities: {len(gt):,}")

    # -----------------------------------------------------------------------
    # Select reproducible holdout
    # -----------------------------------------------------------------------

    holdout_ids = _holdout_ids(
        list(gt.keys()),
        args.sample_size,
        args.seed,
    )

    holdout_set = set(holdout_ids)

    print(f"Selected holdout entities: {len(holdout_ids):,}")
    print()

    # -----------------------------------------------------------------------
    # Load datasets
    # -----------------------------------------------------------------------

    print("Loading Source 1...")
    s1 = _load_tsv(source1_path).filter(
        pl.col("entity_id").is_in(holdout_set)
    )

    print("Loading Source 2...")
    s2 = _load_tsv(source2_path)

    print("Loading Source 3...")
    s3 = _load_tsv(source3_path)

    print(
        f"Source 1 holdout rows: {s1.height:,}"
    )
    print(
        f"Source 2 rows         : {s2.height:,}"
    )
    print(
        f"Source 3 rows         : {s3.height:,}"
    )
    print()

    # -----------------------------------------------------------------------
    # Load trained model
    # -----------------------------------------------------------------------

    print("Loading trained model...")

    model = EntityResolutionModel.load(model_path)

    print(
        f"Model threshold: {model.optimal_threshold:.6f}"
    )
    print()

    # -----------------------------------------------------------------------
    # Prepare Source-1 lookup
    # -----------------------------------------------------------------------

    s1_rows = {
        sid: (
            name or "",
            address or "",
            country or "",
        )
        for sid, name, address, country
        in s1.select(
            [
                "entity_id",
                "business_name",
                "business_address",
                "country",
            ]
        ).iter_rows()
    }

    # Only process countries actually present in the holdout.
    countries = sorted(
        set(
            row[2]
            for row in s1_rows.values()
        )
    )

    print(f"Countries in holdout: {len(countries)}")
    print()

    # -----------------------------------------------------------------------
    # Storage
    # -----------------------------------------------------------------------

    predictions: Dict[str, Set[str]] = {}
    candidate_sets: Dict[str, Set[str]] = {}

    # -----------------------------------------------------------------------
    # Process each country
    # -----------------------------------------------------------------------

    for country in countries:

        country_s1_ids = [
            sid
            for sid in holdout_ids
            if sid in s1_rows
            and s1_rows[sid][2] == country
        ]

        if not country_s1_ids:
            continue

        print(
            f"\nProcessing country: {country or '[EMPTY COUNTRY]'} "
            f"({len(country_s1_ids):,} entities)"
        )

        # Filter S2/S3 for this country.
        country_s2 = s2.filter(
            pl.col("country") == country
        )

        country_s3 = s3.filter(
            pl.col("country") == country
        )

        # Build blocking index.
        index = build_country_inverted_index(
            country_s2,
            country_s3,
            max_key_density=150,
        )

        # Lookup for candidate entity IDs.
        lookup = _s23_lookup(
            pl.concat(
                [country_s2, country_s3],
                how="vertical",
            )
        )

        # -------------------------------------------------------------------
        # Build all candidate pairs for this country first.
        #
        # This lets us call predict_proba() in larger batches instead of
        # repeatedly calling it once for every Source-1 entity.
        # -------------------------------------------------------------------

        all_pair_ids = []
        all_features = []
        pair_owner = []

        for sid in tqdm(
            country_s1_ids,
            desc=f"Blocking/features [{country}]",
            unit="entity",
        ):

            name, address, _ = s1_rows[sid]

            candidates = retrieve_candidates_for_s1(
                name,
                address,
                index,
                max_candidates=args.max_candidates,
            )

            candidate_sets[sid] = set(candidates)

            for mid in candidates:

                if mid not in lookup:
                    continue

                match_name, match_address = lookup[mid]

                feature_vector = compute_pair_features(
                    name,
                    address,
                    match_name,
                    match_address,
                    mid,
                )

                all_pair_ids.append(mid)
                all_features.append(feature_vector)
                pair_owner.append(sid)

        # -------------------------------------------------------------------
        # Predict all candidate pairs for this country.
        # -------------------------------------------------------------------

        if all_features:

            feature_array = np.asarray(
                all_features,
                dtype=np.float32,
            )

            probabilities = model.predict_proba(
                feature_array
            )

            # Convert predictions back to Source-1 entities.
            for sid in country_s1_ids:
                predictions[sid] = set()

            for sid, mid, probability in zip(
                pair_owner,
                all_pair_ids,
                probabilities,
            ):

                if probability >= model.optimal_threshold:
                    predictions[sid].add(mid)

        else:

            for sid in country_s1_ids:
                predictions[sid] = set()

        print(
            f"  Candidate pairs: {len(all_pair_ids):,}"
        )

    # -----------------------------------------------------------------------
    # Evaluation
    # -----------------------------------------------------------------------

    holdout_gt = {
        sid: gt[sid]
        for sid in holdout_ids
        if sid in s1_rows
    }

    # Make sure every evaluated entity has a prediction.
    for sid in holdout_gt:
        predictions.setdefault(sid, set())
        candidate_sets.setdefault(sid, set())

    print()
    print("=" * 70)
    print("CALCULATING METRICS")
    print("=" * 70)

    # -----------------------------------------------------------------------
    # Macro F0.5
    # -----------------------------------------------------------------------

    macro_f05 = compute_macro_f05(
        holdout_gt,
        predictions,
    )

    # -----------------------------------------------------------------------
    # Pair-level metrics
    # -----------------------------------------------------------------------

    true_positive = 0
    false_positive = 0
    false_negative = 0

    candidate_recall_values = []

    # Exact entity-set accuracy
    exact_matches = 0

    # Unmatched-entity accuracy
    unmatched_total = 0
    unmatched_correct = 0

    for sid, expected in holdout_gt.items():

        predicted = predictions.get(
            sid,
            set(),
        )

        candidates = candidate_sets.get(
            sid,
            set(),
        )

        # Pair-level counts.
        true_positive += len(
            expected & predicted
        )

        false_positive += len(
            predicted - expected
        )

        false_negative += len(
            expected - predicted
        )

        # Candidate recall.
        if not expected:
            candidate_recall_values.append(1.0)
        else:
            candidate_recall_values.append(
                len(expected & candidates)
                / len(expected)
            )

        # Exact entity-set accuracy.
        if predicted == expected:
            exact_matches += 1

        # Entities with no true matches.
        if not expected:
            unmatched_total += 1

            if not predicted:
                unmatched_correct += 1

    # -----------------------------------------------------------------------
    # Precision / recall
    # -----------------------------------------------------------------------

    precision_denominator = (
        true_positive + false_positive
    )

    recall_denominator = (
        true_positive + false_negative
    )

    if precision_denominator:
        precision = (
            true_positive
            / precision_denominator
        )
    else:
        precision = 0.0

    if recall_denominator:
        recall = (
            true_positive
            / recall_denominator
        )
    else:
        recall = 0.0

    # -----------------------------------------------------------------------
    # Candidate recall
    # -----------------------------------------------------------------------

    if candidate_recall_values:
        candidate_recall = float(
            np.mean(candidate_recall_values)
        )
    else:
        candidate_recall = 0.0

    # -----------------------------------------------------------------------
    # Exact accuracy
    # -----------------------------------------------------------------------

    if holdout_gt:
        exact_entity_set_accuracy = (
            exact_matches
            / len(holdout_gt)
        )
    else:
        exact_entity_set_accuracy = 0.0

    # -----------------------------------------------------------------------
    # Unmatched accuracy
    # -----------------------------------------------------------------------

    if unmatched_total:
        unmatched_accuracy = (
            unmatched_correct
            / unmatched_total
        )
    else:
        unmatched_accuracy = None

    # -----------------------------------------------------------------------
    # Print final results
    # -----------------------------------------------------------------------

    print()
    print("=" * 70)
    print("HOLDOUT RESULTS")
    print("=" * 70)

    print(
        f"Holdout entities          : {len(holdout_gt):,}"
    )

    print(
        f"Model threshold           : "
        f"{model.optimal_threshold:.6f}"
    )

    print(
        f"Macro F_0.5               : "
        f"{macro_f05:.4f}"
    )

    print(
        f"Pair precision            : "
        f"{precision:.4f}"
    )

    print(
        f"Pair recall               : "
        f"{recall:.4f}"
    )

    print(
        f"Candidate recall ceiling : "
        f"{candidate_recall:.4f}"
    )

    print(
        f"Exact entity-set accuracy : "
        f"{exact_entity_set_accuracy:.4f}"
    )

    if unmatched_accuracy is not None:

        print(
            f"Unmatched accuracy        : "
            f"{unmatched_accuracy:.4f} "
            f"({unmatched_correct:,}/{unmatched_total:,})"
        )

    else:

        print(
            "Unmatched accuracy        : "
            "no unmatched entities in holdout"
        )

    print()
    print("=" * 70)
    print(
        "This is a labeled training-holdout diagnostic."
    )
    print(
        "The official test score requires submission because "
        "test ground truth is hidden."
    )
    print("=" * 70)

    return 0


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    raise SystemExit(main())